### PR TITLE
convert from ASCIIdoc to Markdown

### PR DESCRIPTION
**Pull request by cbolz**
This PR converts the ASCIIDoc document "advanced tower lab" to Markdown

### CODE REVIEW

**Comment by ericzolf** [comment]
I browsed quickly through it, and it looks roughly OK (we probably can only fix the individual issues as we see them).

Just a few generic comments you could fix in a swipe:

- there are spurious backslashes throughout the rendered documents, especially in URL examples
- the "click here for the solution" drop-down doesn't work as rendered by GitHub, is it solely a GitHub issue and we don't care because we'll render ourselves, or do we have a problem?
- There are many "click the _20_ button" sentences (20 is a link to a non-existing graphic).

**Comment by cbolz** [comment]
good point about the images: they seem to be missing in this repo (only the adoc file was on github). On the people page, the images are embedded in the HTML code.
@goetzrieger do you have to original images, so we can embed them?

**Comment by cbolz** [comment]
GitHub can also do collapse - I'll fix it...

**Comment by cbolz** [comment]
we still need to double check the whole document - this was a half automated mass convert, not a manual review of all the chapters - in particular the "advanced tower content" needs reviewing

**Comment by ericzolf** [comment]
backslash before URL, e.g. at https://github.com/cbolz/ansible-labs-summit2020/tree/tower-markdown/ansible-tower-advanced/3.1-intro (and I only clicked on this one file, so either I'm very lucky or there are more of those):

```
ansible-labs-summit2020]$ grep -r '\\\\http' .
./ansible-tower-advanced/3.5-tower-cluster-jobs/README.md:        **\\https://tower.ewl05.sandbox309.opentlc.com/api/v2/jobs/\<ID\>/**
./ansible-tower-advanced/3.2-clustering/README.md:  - **\\https://tower1.\<GUID\>.sandbox951.opentlc.com**
./ansible-tower-advanced/3.2-clustering/README.md:  - **\\https://tower2.\<GUID\>.sandbox951.opentlc.com**
./ansible-tower-advanced/3.2-clustering/README.md:  - **\\https://tower3.\<GUID\>.sandbox951.opentlc.com**
./ansible-tower-advanced/3.10-structured-content/README.md:**\\http://control-\<GUID\>.rhpds.opentlc.com/gitea**.
./ansible-tower-advanced/3.10-structured-content/README.md:**\\http://control.example.com/gitea/git/shared-apache-role**.
./ansible-tower-advanced/3.1-intro/README.md:**\\https://github.com/goetzrieger/ansible-labs/blob/master/tower/ansible\_tower\_advanced.adoc**
```

I suspect that you also need to search for `\<` and fix them (there are quite many of those).

**Comment by cbolz** [comment]
> backslash before URL, e.g. at https://github.com/cbolz/ansible-labs-summit2020/tree/tower-markdown/ansible-tower-advanced/3.1-intro (and I only clicked on this one file, so either I'm very lucky or there are more of those):
> 
> ```
> ansible-labs-summit2020]$ grep -r '\\\\http' .
> ./ansible-tower-advanced/3.5-tower-cluster-jobs/README.md:        **\\https://tower.ewl05.sandbox309.opentlc.com/api/v2/jobs/\<ID\>/**
> ./ansible-tower-advanced/3.2-clustering/README.md:  - **\\https://tower1.\<GUID\>.sandbox951.opentlc.com**
> ./ansible-tower-advanced/3.2-clustering/README.md:  - **\\https://tower2.\<GUID\>.sandbox951.opentlc.com**
> ./ansible-tower-advanced/3.2-clustering/README.md:  - **\\https://tower3.\<GUID\>.sandbox951.opentlc.com**
> ./ansible-tower-advanced/3.10-structured-content/README.md:**\\http://control-\<GUID\>.rhpds.opentlc.com/gitea**.
> ./ansible-tower-advanced/3.10-structured-content/README.md:**\\http://control.example.com/gitea/git/shared-apache-role**.
> ./ansible-tower-advanced/3.1-intro/README.md:**\\https://github.com/goetzrieger/ansible-labs/blob/master/tower/ansible\_tower\_advanced.adoc**
> ```
> 
> I suspect that you also need to search for `\<` and fix them (there are quite many of those).

fixed

**Pull request merged**
